services:
  app:
    image: python:3.12
    container_name: ICB

    volumes:
      - ./app:/ICB
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["sh", "/entrypoint.sh"]
    ports:
      - "8060:8060"
    restart: always
