services:
  app:
    image: python:3.12
    container_name: ICB
    working_dir: /app
    user: "1000:1000"
    volumes:
      - ./app:/app
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["sh", "/entrypoint.sh"]
    ports:
      - "8060:8060"
    restart: always
